### ISSUE TITLE
Navigating "Back to Game" from guest avatar results in 404

### ISSUE THREAD

**Issue by rboccabe** [HangmanWithFriends/Hangman#6]
Description: When logged in to the lobby page, a user who selects the "Back to Game" option from the menu box on the avatar encounters a 404 error.

Severity: Medium - The 404 error is confusing for the user, but whenever an error occurs most users just press "back" and in this case they would be back to a webpage on the site where navigation should otherwise work correctly.

Repro Steps:
1.) Login as a guest
2.) Click on the avatar in the corner of the screen.
3.) Select "Back to Game" from the list of options.

Actual Behavior: The user encounters a 404 error.

Expected Behavior: The user is brought back to a game in progress if there is one. If there is no game in progress, this option should not be available from the avatar's menu.

**Comment by nsanders1994** [comment]
We've decided to remove this option from the menu altogether because it would be unlikely for two players to return to the same game at the same time. A better design is for the players play in single sessions. Ultimately, we do not think that this feature would be used.
